---
title: "Surveillance Report"
resource_files:
- rstudio-template.pptx
author: "Your Name"
date: "2023-11-16"
output: 
  powerpoint_presentation:
    reference_doc: rstudio-template.pptx
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r, eval=TRUE, echo=FALSE}
# load packages
pacman::p_load(
  rio,          # for importing data
  here,         # for locating files
  janitor,
  lubridate,    # for date cleaning 
  scales,       # date formatting
  flextable,    # HTML tables
  tidyverse     # for data management and visualization
)
```


```{r, eval=T, echo=FALSE}
# import the clean data
surv <- rio::import(here("data", "clean", "linelist_combined_20141201.rds"))
```


## Epi Curve

```{r, echo=F, warning=F, message=F}
# Make weekly breaks, on Mondays
weekly_breaks <- seq.Date(
    from = floor_date(min(surv$date_onset, na.rm=T), "week", week_start = 1), 
    to   = ceiling_date(max(surv$date_onset, na.rm=T), "week", week_start = 1), 
    by   = "week")     


# make the plot
ggplot(data = surv) + 
    geom_histogram(
    mapping = aes(x = date_onset), 
    breaks = weekly_breaks, 
    closed = "left",
    color = "darkblue",     
    fill = "lightblue")+ 
  scale_x_date(
    expand            = c(0,0),            
    date_breaks       = "4 weeks",        
    date_minor_breaks = "week",           
    labels            = scales::label_date_short())+ 
  scale_y_continuous(expand = c(0,0))+            
  theme_minimal()+                
  theme(plot.caption = element_text(hjust = 0, face = "italic"), 
        axis.title = element_text(face = "bold"))+    
  labs(
    title    = "Weekly incidence of cases",
    subtitle = "Subtitle here",
    x        = "Week of symptom onset",
    y        = "Weekly incident cases reported",
    caption  = stringr::str_glue("n = {nrow(surv)}; Case onsets range from {format(min(surv$date_onset, na.rm=T), format = '%a %d %b %Y')} to {format(max(surv$date_onset, na.rm=T), format = '%a %d %b %Y')}\n{nrow(surv %>% filter(is.na(date_onset)))} cases missing date of onset and not shown"))

```

## Outbreak Details

- Outbreak peaks with almost 40 cases the week of September 22, 2014.
- The outbreak began the week of May 5, 2014.

## Deaths By Age

```{r}
surv %>%
  mutate(age_cat = fct_na_value_to_level(age_cat, "Unknown")) %>% # NA to "Unknown"
  mutate(outcome = fct_na_value_to_level(outcome, "Unknown")) %>% 
  tabyl(age_cat, outcome) %>%                 # make table
  adorn_totals(where = "both") %>%            # add total and column
  adorn_percentages(denominator = "row") %>%  # convert counts to proportions
  adorn_pct_formatting(digits = 1) %>%        # convert proportions to percents
  adorn_ns("front") %>%                       # add counts to table
  qflextable() %>%                            # convert to flextable
  bg(part = "all", bg = "white")              # make background white


```

## Percent with Symptom

```{r, echo=F}
# Make table of symptoms and their proportions
sym_data <- surv %>%                                             # begin with linelist
  select(c(case_id, fever, chills, cough, aches, vomit)) %>%     # select columns
  pivot_longer(                                                  # pivot longer
    cols = -case_id,                                  
    names_to = "symptom_name",
    values_to = "symptom_is_present") %>%
  mutate(                                                        # replace missing values
    symptom_is_present = replace_na(symptom_is_present, "unknown")) 
  
  # Make the actual plot
  ggplot(                    
    data = sym_data,
    mapping = aes(
      x = symptom_name,
      fill = symptom_is_present))+
  geom_bar(position = "fill", # make bars extend to 100%
           col = "black") +   # bar edges are black                 
  theme_classic() +
  scale_y_continuous(labels = scales::percent_format())+ # convert proportions to percents
  labs(
    x = "Symptom",
    y = "Percent of cases",
    fill = "Symptom status"   # adjust legend title
  )
```

